### ISSUE TITLE
API access no longer working - Unable to decode JSON from response to get_session(). Received 'None'

### ISSUE THREAD

**Issue by fusenuk** [aruba/aoscx-ansible-collection#61]
A script that has been used previously has suddenly stopped working and trying multiple different examples of simple API based YML files also show the same error -

`ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_session(). Received 'None'.\n",`

Ansible version - 

```
mw284@cox:~/ansible-acls$ ansible-3 --version
ansible-3 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mw284/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-3
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

test-api.yml -

```
---
- name: Test a simple connection to the API
  hosts: "{{ routers }}"
  collections:
    - arubanetworks.aoscx
  any_errors_fatal: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx connection method
    ansible_acx_no_proxy: True
    ansible_aoscx_validate_certs: False
    ansible_aoscx_use_proxy: False

  tasks:
    - name: Gather facts
      aoscx_facts:

    - name:
      ansible.builtin.debug:
        msg:
          - " {{ (ansible_facts['net_interfaces']) }} "
          - " {{ (ansible_facts['net_software_info']) }} "
```

Command being used to execute -

`ansible-playbook -vvv test-api.yml -u mw284sadmin --ask-pass --extra-vars "{'routers':'cdc-drsrv-t0-a, cdc-drsrv-t0-b'}"`

Error output -

```
mw284@cox:~/ansible-acls$ ansible-playbook -vvv test-api.yml -u mw284sadmin --ask-pass --extra-vars "{'routers':'cdc-drsrv-t0-a, cdc-drsrv-t0-b'}"
ansible-playbook 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mw284/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
SSH password:
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: test-api.yml ********************************************************************************************************************************************************************************************************************
1 plays in test-api.yml

PLAY [Deploy ACLs to Aruba CX Routers - API] **********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************
task path: /home/mw284/ansible-acls/test-api.yml:2
<cdc-drsrv-t0-b> ESTABLISH LOCAL CONNECTION FOR USER: mw284
<cdc-drsrv-t0-b> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt `"&& mkdir "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589 `" && echo ansible-tmp-1676566606.6707375-18365-1252136405589="` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589 `" ) && sleep 0'
<cdc-drsrv-t0-a> ESTABLISH LOCAL CONNECTION FOR USER: mw284
<cdc-drsrv-t0-a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt `"&& mkdir "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759 `" && echo ansible-tmp-1676566606.6786718-18364-66216398003759="` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/setup.py
<cdc-drsrv-t0-b> PUT /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/tmpspx2rpfs TO /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589/AnsiballZ_setup.py
<cdc-drsrv-t0-b> EXEC /bin/sh -c 'chmod u+x /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589/ /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589/AnsiballZ_setup.py && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/setup.py
<cdc-drsrv-t0-a> PUT /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/tmp5ul74vj3 TO /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759/AnsiballZ_setup.py
<cdc-drsrv-t0-a> EXEC /bin/sh -c 'chmod u+x /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759/ /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759/AnsiballZ_setup.py && sleep 0'
<cdc-drsrv-t0-b> EXEC /bin/sh -c '/usr/bin/python3 /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589/AnsiballZ_setup.py && sleep 0'
<cdc-drsrv-t0-a> EXEC /bin/sh -c '/usr/bin/python3 /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759/AnsiballZ_setup.py && sleep 0'
<cdc-drsrv-t0-a> EXEC /bin/sh -c 'rm -f -r /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6786718-18364-66216398003759/ > /dev/null 2>&1 && sleep 0'
ok: [cdc-drsrv-t0-a]
<cdc-drsrv-t0-b> EXEC /bin/sh -c 'rm -f -r /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566606.6707375-18365-1252136405589/ > /dev/null 2>&1 && sleep 0'
ok: [cdc-drsrv-t0-b]
META: ran handlers

TASK [Gather facts] ***********************************************************************************************************************************************************************************************************************
task path: /home/mw284/ansible-acls/test-api.yml:16
<cdc-drsrv-t0-a> ESTABLISH LOCAL CONNECTION FOR USER: mw284
<cdc-drsrv-t0-a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt `"&& mkdir "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487 `" && echo ansible-tmp-1676566612.060997-18702-23207485783487="` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487 `" ) && sleep 0'
<cdc-drsrv-t0-b> ESTABLISH LOCAL CONNECTION FOR USER: mw284
<cdc-drsrv-t0-b> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt `"&& mkdir "` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887 `" && echo ansible-tmp-1676566612.1006916-18703-14763677704887="` echo /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887 `" ) && sleep 0'
Using module file /home/mw284/.ansible/collections/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py
<cdc-drsrv-t0-b> PUT /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/tmpwxlap19e TO /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py
<cdc-drsrv-t0-b> EXEC /bin/sh -c 'chmod u+x /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/ /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py && sleep 0'
Using module file /home/mw284/.ansible/collections/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py
<cdc-drsrv-t0-a> PUT /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/tmpms97vbie TO /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py
<cdc-drsrv-t0-a> EXEC /bin/sh -c 'chmod u+x /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/ /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py && sleep 0'
<cdc-drsrv-t0-b> EXEC /bin/sh -c '/usr/bin/python3 /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py && sleep 0'
<cdc-drsrv-t0-a> EXEC /bin/sh -c '/usr/bin/python3 /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py && sleep 0'
<cdc-drsrv-t0-b> EXEC /bin/sh -c 'rm -f -r /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/ > /dev/null 2>&1 && sleep 0'
<cdc-drsrv-t0-a> EXEC /bin/sh -c 'rm -f -r /home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 156, in _exec_jsonrpc
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py", line 436, in <module>
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py", line 270, in main
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py", line 82, in get_pyaoscx_session
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py", line 47, in __init__
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 184, in __rpc__
  File "/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 166, in _exec_jsonrpc
ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_session(). Received 'None'.
fatal: [cdc-drsrv-t0-b]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 156, in _exec_jsonrpc\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.1006916-18703-14763677704887/AnsiballZ_aoscx_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 436, in <module>\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 270, in main\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 82, in get_pyaoscx_session\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 47, in __init__\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 184, in __rpc__\n  File \"/tmp/ansible_aoscx_facts_payload_n0555gfa/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 166, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_session(). Received 'None'.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 156, in _exec_jsonrpc
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py", line 436, in <module>
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py", line 270, in main
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py", line 82, in get_pyaoscx_session
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py", line 47, in __init__
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 184, in __rpc__
  File "/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 166, in _exec_jsonrpc
ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_session(). Received 'None'.
fatal: [cdc-drsrv-t0-a]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 156, in _exec_jsonrpc\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/mw284/.ansible/tmp/ansible-local-183414urrsekt/ansible-tmp-1676566612.060997-18702-23207485783487/AnsiballZ_aoscx_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 436, in <module>\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 270, in main\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 82, in get_pyaoscx_session\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 47, in __init__\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 184, in __rpc__\n  File \"/tmp/ansible_aoscx_facts_payload_vrwr_x0f/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py\", line 166, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_session(). Received 'None'.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
cdc-drsrv-t0-a             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
cdc-drsrv-t0-b             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

The device is showing it accepted the connection -

```
2023-02-16T16:53:51.891357+00:00 cdc-drsrv-t0-a hpe-restd[2859]: Event|4657|LOG_INFO|AMM|-|User mw284sadmin logged out of REST session from 129.12.21.134
2023-02-16T16:53:51.889873+00:00 cdc-drsrv-t0-a hpe-restd[2859]: Event|4608|LOG_INFO|AMM|-|Authorization allowed for user mw284sadmin, for resource SessionMgmt, with action POST
2023-02-16T16:53:51.779651+00:00 cdc-drsrv-t0-a hpe-restd[2859]: Event|4655|LOG_INFO|AMM|-|User mw284sadmin logged in from 129.12.21.134 through REST session
2023-02-16T16:53:51.779527+00:00 cdc-drsrv-t0-a hpe-restd[2859]: Event|4602|LOG_INFO|AMM|-|Authentication succeeded for user mw284sadmin in session HnmRBPW-v-jwFt3itJnsnA==
```

Device details - 
```

cdc-drsrv-t0-a# show version
-----------------------------------------------------------------------------
ArubaOS-CX
(c) Copyright 2017-2022 Hewlett Packard Enterprise Development LP
-----------------------------------------------------------------------------
Version      : LL.10.10.1010
Build Date   : 2022-09-21 17:19:31 UTC
Build ID     : ArubaOS-CX:LL.10.10.1010:e21f37143c83:202209211618
Build SHA    : e21f37143c830c9ca5d4c5b3384f48656036fbe2
Active Image : primary

Service OS Version : LL.01.10.0001
BIOS Version       : LL.01.0001
```

I've made sure things are up to date using the following -

```
pip3 install pyaoscx
ansible-galaxy-3 collection install arubanetworks.aoscx
cd ~/.ansible/collections/ansible_collections/arubanetworks/aoscx/
ansible-galaxy-3 install -r requirements.yml
python3 -m pip install -r requirements.txt
ansible-galaxy-3 collection install arubanetworks.aoscx -f
ansible-galaxy-3 collection install ansible.netcommon -f
ansible-galaxy-3 collection install ansible.utils -f
```

The original script that worked but now doesn't tries to delete an ACL and comes back with this same error of not being able to interpret the JSON response and instead showing 'None.' 

When that stopped working I looked around previous Issues to try and find simple API based ansible scripts to pull info and settled on the above YML file which gives the exact same response.

Any ideas for what may be the cause or ideas for modifying the python code to try to tease out what exactly the response is, if it isn't JSON (maybe even just read the HTTP status codes to see if the request is failing?)

**Comment by tchiapuziowong** [comment]
@fusenuk couple of troubleshooting questions:
- what version of `ansible.netcommon` do you have installed?
- has anything changed in your environment? (firmware, python version, collection version?)
- if you remove `ansible_python_interpreter` in your playbook does that improve/change the error at all?

**Comment by fusenuk** [comment]
Thanks for the quick reply [tchiapuziowong](https://github.com/tchiapuziowong)

`Netcommon is "version": "3.1.0",`

Weirdly, I see the normal method of detecting that as 'ansible-galaxy collection list' but my version of that executable doesn't have that option -
```
mw284@cox:~$ ansible-galaxy-3 collection list
usage: ansible-galaxy-3 collection [-h] COLLECTION_ACTION ...
ansible-galaxy-3 collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```
I read the contents of the MANIFEST file to get that version number


Something must have changed as this was working for multiple months, across multiple users on the same server running their own copies of the ansible modules and yml scripts, I'm just not sure what. 
The firmware on the switches is definitely the same. 
YUM logs show the only python updates since this last worked are 

```
Jan 31 03:07:14 Updated: python-sssdconfig-1.16.5-10.el7_9.15.noarch
Jan 31 03:07:15 Updated: python-sss-1.16.5-10.el7_9.15.x86_64
```

If I remove the python3 interpreter line then the script fails for a different reason. The final line of the trace shows 

```
File "/tmp/ansible_aoscx_facts_payload_a9ZmeJ/ansible_aoscx_facts_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
```

One of my ex-colleagues initially set this up so I can't remember the exact reason but Python3 was needed for one of the modules to work properly, possibly a Cisco module that we use side by side for other device management. That is why we use the '-3' ansible executables and force the script to use python3.

**Comment by alagoutte** [comment]
There is a [bug](https://github.com/ansible-collections/ansible.netcommon/pull/523) for some [module](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/237) with ansible.netcommon 5.0.0
