### ISSUE TITLE
ansible.module_utils.connection.ConnectionError: Method not found

### ISSUE THREAD

**Issue by olivier-magloire** [aruba/aoscx-ansible-collection#73]
Just got two 6200F to configure for a customer and I can not get the example playbook to run at all, see the stacktrace below. Installed as described in https://github.com/aruba/aoscx-ansible-collection#installation
- ArubaOS-CX Version : ML.10.07.0030
- ansible [core 2.14.5]
- python version = 3.10.10

what am i missing?
```
all:
  hosts:
    lssw01:
      ansible_host: lssw01
      ansible_hostname: swdc01
      ansible_user: admin
      ansible_password: admin
      ansible_network_os: arubanetworks.aoscx.aoscx
      ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx connection method
      ansible_aoscx_validate_certs: False
      ansible_aoscx_use_proxy: False
      ansible_acx_no_proxy: True
```
```
- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
  - name: Create L3 Interface 1/1/3
    aoscx_l3_interface:
      interface: 1/1/3
      description: Uplink_Interface
      ipv4:
        - 10.20.1.3/24
      ipv6:
        - 2000:db8::1234/64
```
```
TASK [Create L3 Interface 1/1/3] **********************************************************************************************
task path: /home/olivierm/git/playbook2.yml:8
<lssw01> ESTABLISH LOCAL CONNECTION FOR USER: olivierm
<lssw01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg `"&& mkdir "` echo /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728 `" && echo ansible-tmp-1682589112.8025367-250808-260147464691728="` echo /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728 `" ) && sleep 0'
Using module file /home/olivierm/.ansible/collections/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_l3_interface.py
<lssw01> PUT /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/tmpa_g1m400 TO /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py
<lssw01> EXEC /bin/sh -c 'chmod u+x /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/ /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py && sleep 0'
<lssw01> EXEC /bin/sh -c '/usr/bin/python3 /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py && sleep 0'
<lssw01> EXEC /bin/sh -c 'rm -f -r /home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py", line 107, in <module>
    _ansiballz_main()
  File "/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_l3_interface', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_l3_interface', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_l3_interface.py", line 360, in <module>
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_l3_interface.py", line 256, in main
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py", line 472, in __init__
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py", line 496, in get_switch_platform
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py", line 385, in get
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py", line 235, in get
  File "/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
fatal: [lssw01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/olivierm/.ansible/tmp/ansible-local-250795udzq1edg/ansible-tmp-1682589112.8025367-250808-260147464691728/AnsiballZ_aoscx_l3_interface.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_l3_interface', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_l3_interface', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_l3_interface.py\", line 360, in <module>\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_l3_interface.py\", line 256, in main\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 472, in __init__\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 496, in get_switch_platform\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 385, in get\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 235, in get\n  File \"/tmp/ansible_aoscx_l3_interface_payload_hd71_8gs/ansible_aoscx_l3_interface_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by alagoutte** [comment]
Hi @olivier-magloire,

What aoscx ansible collection release ? and ansible.netcommon ?

**Comment by tchiapuziowong** [comment]
@olivier-magloire your value of `ansible_hostname` is that the entire DNS address of the switch? are you able to ping that address from the Ansible vm you're using?

can you please provide the results from the following commands?
`ansible-galaxy collection list`
`ansible --version`
`pip list | grep aoscx`
`python3 -m pip list | grep aoscx`

**Comment by olivier-magloire** [comment]
@tchiapuziowong thanks for the questions, this lead me to the root cause.
i had executed the pip install on the wrong requirements.txt (from a completely different project) so i was missing the aoscx module.

i was a bit confused by the readme formatting, find a proposal for simplification here: https://github.com/aruba/aoscx-ansible-collection/pull/74
